name: Build and Deploy Vue.js App

on:
  push:
    branches:
      - main  # Set to the branch name you use for releases
    tags: ['v*.*.*']
  pull_request:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Set this to the node version you use

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js project
        run: npm run build
      
      - name: Upload dist directory to workspace
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  call-docker-build:
    needs: build_vue
    uses: ethdevops/workflows/.github/workflows/basic-docker-build.yaml@main
    with:
      use_artifact: true
      artifact_name: dist
      artifact_path: dist
    secrets:
      docker_registry_user: ${{ secrets.DOCKER_REGISTRY_USER }}
      docker_registry_password: ${{ secrets.DOCKER_REGISTRY_SECRET }}
 
